### ISSUE TITLE
Custom reference styles

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#15]
Would it be an option to provide a default reference formatting style like the one we currently have, and in addition allow for a custom `.hbs` file in the configuration?

This way, there is no need to focus on a one-fits-all style. Default to something familiar and convenient (like the current style), and possibly provide `.hbs` files of common stlyes for download.

**Comment by francisco-perez-sorrosal** [comment]
Sounds nice to have! I guess we'll need a new config param like `render-bib-style-filename` or something similar, which if present, will override the default style and will have to point to the `.hbs` config file. In the documentation, we'll have to let the user know where to place the `.hbs` file (I guess the root of the mdbook) and which are the available attributes in the [`BibItem` struct](https://github.com/francisco-perez-sorrosal/mdbook-bib/blob/a8bf7d4aee0094311e9d055f0466f0bebdabce23/src/lib.rs#L151) that he can use in the ad-hoc handlebars style.

**Comment by mlange-42** [comment]
> I guess we'll need a new config param like `render-bib-style-filename` or something similar

Maybe a bit shorter, like `style-template` or `ref-style`

> In the documentation, we'll have to let the user know where to place the `.hbs` file (I guess the root of the mdbook)

I would simply go for a path relative to the book root. This way, users can also place their template(s) in a sub-directory.

> and which are the available attributes

We may consider creating a separate document like `docs/manual.md` where we document config options, style templates, etc. to not overload the README. By the way... can we make the README title shorter (e.g. simply `mdbook-bib`) and instead add a summary sentence?
