### ISSUE TITLE
Consolidate config style with either underscores or hyphens

### ISSUE THREAD

**Issue by francisco-perez-sorrosal** [francisco-perez-sorrosal/mdbook-bib#16]
Up to now the two options added zotero_user_id and render-bib do not follow a common pattern for the word separators. We should consolidate this, either using _ or -.

**Comment by mlange-42** [comment]
+1 for `-`. It looks better and is faster to type.

**Comment by francisco-perez-sorrosal** [comment]
And the winner is... hyphens!
