### ISSUE TITLE
Release v0.3.0 binaries

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#23]
Can we release binaries for the 0.3.0 version, so they can be downloaded by CI scripts to save the effort of building them using Cargo?

We could change the trigger in `release.yaml` to release creation:

```
on:
  release:
    types: [ created ]
```

**Comment by francisco-perez-sorrosal** [comment]
Done: https://github.com/francisco-perez-sorrosal/mdbook-bib/releases
