### ISSUE TITLE
[Rendering] Reference list - allow for selecting citation key

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#4]
The current rendering of the references does not allow C&P of the citation key due to popup on hover.
Personally, I find the popup behaviour with motion in the following references a bit distracting.

Maybe it could be a solution to not show the citation key, but to provide a small link that copies it to the clipboard? Or to include the key in the `details` tags so it opens only on click?

**Comment by francisco-perez-sorrosal** [comment]
Addressed in #6
