### ISSUE TITLE
Alexander is not Alex and er

### ISSUE THREAD

**Issue by raspofabs** [francisco-perez-sorrosal/mdbook-bib#44]
https://github.com/francisco-perez-sorrosal/mdbook-bib/blob/34f3588e51da45f8a4f528f4095b1c28858440d4/src/lib.rs#L319C25-L319C25

I have an author with "and" in their name, notably, Christopher Alexander, but I imagine anyone with an and in their name will suffer the same split personality fate.

**Comment by mlange-42** [comment]
Thanks for reporting: Just started the CI tests on #45.

**Comment by raspofabs** [comment]
Hmm, seems like the nightly build (1.72.0) breaks something. Can you set the actions to only stable over nightly?

**Comment by francisco-perez-sorrosal** [comment]
Thank you @raspofabs  and @mlange-42  for reporting, fixing and testing this. I'll test it also myself and I'll create a new version ASAP.
