### ISSUE TITLE
[Feature] Make title of bibliography configurable

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#6]
An optional config argument to use an alternative title for the bib chapter, e.g. `References`.

**Comment by mlange-42** [comment]
Another option to allow for this feature would be to provide an option for a placeholder (and potentially a path) for placing the bibliography, like I did it [here in yarner-bib](https://github.com/mlange-42/yarner-bib#options).

The default could be the current behaviour, while replacement is used if option `placeholder` is given.

This way, users have full flexibility where to place the bibliography (e.g. on the same page as the glossary).

**Comment by francisco-perez-sorrosal** [comment]
Done in #28
